---
version: '2'

services:
  unifi:
    image: ryansch/unifi-rpi:latest
    container_name: unifi
    restart: unless-stopped
    environment:
      JAVA_OPTS: -Xmx512M
    ports:
      - 8080:8080      # Device -> controller
      - 8888:8443      # Web UI
      # - 8843:8843      # HTTPS redirection
      # - 8880:8880      # HTTP redirect
      - 3478:3478/udp  # STUN
    volumes:
      - config:/var/lib/unifi
      - log:/usr/lib/unifi/logs
      - log2:/var/log/unifi
      - run:/usr/lib/unifi/run
      - run2:/run/unifi
      - work:/usr/lib/unifi/work
volumes:
  config:
    driver: local
  log:
    driver: local
  log2:
    driver: local
  run:
    driver: local
  run2:
    driver: local
  work:
    driver: local
